### ISSUE TITLE
どんな世界観のサイトにするか

### ISSUE THREAD

**Issue by oshiminn** [circus-design/circus#14]
## タイトル
トンマナ決める

## 概要
このサイトを訪れた人にどういう印象を与えたい？

## どうなったら成功か（issueを閉じるか）
イメージボードやイメージの言葉ができたら完成

**Comment by nakaj1man** [comment]
おしみん&フジケンと話し合った結果、僕の方で決めることになったので本件クローズします。
メンバーには随時共有します。
