### ISSUE TITLE
Plant全メンバー追加

### ISSUE THREAD

**Issue by oshiminn** [circus-design/circus#17]
## タイトル
issueの呼称を書く

## 概要
sketchのver管理をPlantを使ってみる
(https://projects.plantapp.io/)

## どうなったら成功か（issueを閉じるか）
メンバーに全員追加

**Comment by oshiminn** [comment]
ここに登録したメルアドをここに追加してください
@chanchihiro @Kenta-Nakajima

**Comment by chanchihiro** [comment]
全員メンバーにいることを確認した
